name: flutter_nnnoiseless
description: "Recurrent neural network for audio noise reduction ."
repository: https://github.com/sk3llo/flutter_nnnoiseless.git
version: 1.0.0

environment:
  sdk: ^3.7.2
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.11.1
  path: ^1.9.1
  wav: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  ffi: ^2.0.2
  ffigen: 19.0.0
  integration_test:
    sdk: flutter

topics:
  - 'audio'
  - 'noise'
  - 'RNN'
  - 'artificial-intelligence'

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true