// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `denoise_frames`, `resample_in`, `resample_out`, `to_pcm16`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DenoiseSession>>
abstract class DenoiseSession implements RustOpaqueInterface {
  /// Creates a new denoising session.
  ///
  /// * `sample_rate` - sample rate of the PCM data passed to [process].
  ///   Output audio is returned at the same rate.
  /// * `wet` - dry/wet mix: 1.0 = fully denoised, 0.0 = passthrough.
  static DenoiseSession create({
    required int sampleRate,
    required double wet,
  }) => RustLib.instance.api.crateApiSessionDenoiseSessionCreate(
    sampleRate: sampleRate,
    wet: wet,
  );

  /// Drains any internally buffered audio, padding with silence as needed.
  ///
  /// Call once at the end of a stream to receive the tail of the audio.
  Future<Uint8List> flush();

  /// Denoises a chunk of raw 16-bit PCM mono audio.
  ///
  /// Designed to be called repeatedly with consecutive chunks (e.g. from a
  /// microphone stream). Samples are buffered internally, so the returned
  /// audio length may differ from the input length on any single call.
  Future<DenoiseOutput> process({required List<int> input});

  /// Clears all internal state so the session can be reused for a new
  /// stream without artifacts from the previous one.
  Future<void> reset();
}

/// The result of processing one chunk of audio through a [DenoiseSession].
class DenoiseOutput {
  /// Denoised 16-bit PCM mono audio at the session's sample rate.
  ///
  /// May be empty (or shorter/longer than the input) while the session
  /// buffers samples towards full 10ms frames; timing evens out across
  /// consecutive calls.
  final Uint8List audio;

  /// Voice activity probability (0.0..=1.0) for each 10ms frame that was
  /// processed during this call, in order.
  final Float32List voiceProbabilities;

  const DenoiseOutput({required this.audio, required this.voiceProbabilities});

  @override
  int get hashCode => audio.hashCode ^ voiceProbabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DenoiseOutput &&
          runtimeType == other.runtimeType &&
          audio == other.audio &&
          voiceProbabilities == other.voiceProbabilities;
}
